# Generated by Django 5.2.8 on 2025-11-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredients_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quanity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
