# Generated by Django 5.2.8 on 2025-11-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredients_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
