# Generated by Django 5.2.8 on 2025-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipierequirements',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
