# Generated by Django 5.2.8 on 2025-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_recipierequirements_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipierequirements',
            name='required_units',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('oz', 'Ounces (oz)'), ('pcs', 'Pieces')], default='pcs', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='units',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('oz', 'Ounces (oz)'), ('pcs', 'Pieces')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='recipierequirements',
            unique_together={('menu_item', 'ingredient')},
        ),
    ]
