# Generated by Django 5.2.8 on 2025-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_recipierequirements_required_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='units',
            field=models.CharField(choices=[('Kg', 'Kilogram (kg)'), ('G', 'Gram (g)'), ('L', 'Liter (l)'), ('Ml', 'Milliliter (ml)'), ('Oz', 'Ounces (oz)'), ('Pcs', 'Pieces')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recipierequirements',
            name='required_units',
            field=models.CharField(choices=[('Kg', 'Kilogram (kg)'), ('G', 'Gram (g)'), ('L', 'Liter (l)'), ('Ml', 'Milliliter (ml)'), ('Oz', 'Ounces (oz)'), ('Pcs', 'Pieces')], default='Pcs', max_length=5),
        ),
    ]
